dist: trusty
language: rust
services: docker
sudo: required
env:
  global:
    - CRATE_NAME=rundeck

matrix:
  include:
    # Linux
    - env: TARGET=i686-unknown-linux-gnu
    - env: TARGET=i686-unknown-linux-musl
    - env: TARGET=x86_64-unknown-linux-gnu
    - env: TARGET=x86_64-unknown-linux-musl

    # OSX
    - env: TARGET=i686-apple-darwin
      os: osx
    - env: TARGET=x86_64-apple-darwin
      os: osx

    # *BSD
    - env: TARGET=i686-unknown-freebsd DISABLE_TESTS=1

    # Other architectures
    - env: TARGET=aarch64-unknown-linux-gnu
    - env: TARGET=armv7-unknown-linux-gnueabihf
    - env: TARGET=mips-unknown-linux-gnu
    - env: TARGET=mips64-unknown-linux-gnuabi64
    - env: TARGET=mips64el-unknown-linux-gnuabi64
    - env: TARGET=mipsel-unknown-linux-gnu
    - env: TARGET=powerpc-unknown-linux-gnu
    - env: TARGET=powerpc64-unknown-linux-gnu
    - env: TARGET=powerpc64le-unknown-linux-gnu
    - env: TARGET=s390x-unknown-linux-gnu DISABLE_TESTS=1

    # Testing other channels
    - env: TARGET=x86_64-unknown-linux-gnu
      rust: nightly
    - env: TARGET=x86_64-apple-darwin
      os: osx
      rust: nightly

before_install: set -e

install:
  - sh ci/setup.sh
  - source ~/.cargo/env || true

script:
  - bash ci/run.sh

after_script: set +e

before_deploy:
  - sh ci/before_deploy.sh

deploy:
  api_key:
    secure: GV7auOrP6YpQtwTdS3zOcBfCYIbWZEdtaNdZTEYVRo7dxa4uqZfVW/pR1gUf23BuHnArotduzZn7s3Ww5p4WfxuI7k0fNkPwDLWZeWV6XERVRBEf1Rlopkn3QV+YrbRO5nUXcgB+DCbU4AjrWWM1h77QZmieVmH+oLH2bf4qUhLftRH4puYuZS37/q4wbvGDPNNTLWbrhQCod+/1jTDwLCyqKVSqfX6UN7Sc4MX4QqM2UsVO6UsFPc7cHQhVmpJdqgQuhBVbwofzVZfXpvmTbfpGmZ43Se3wBziGSbEo2A/lR8vEJDLYffZ02m0oyS+8KEdl9cbkBrAE+0ttxfFXJ4MLMvPBQsqQFgReRtk+Jnps7dEa32disvEctqixPPC+WCVwWYZT5f/ePxJbcATdicydupJRMvfm/y+wKjUs5WqFvxEf92HMJS5okJGXkrqPXH04Uqktan95BipplJS8IYIKDh04Dmsb/t689kazth0Md2DGUaVFS4rCpP/grHe9no/Bv2VkY56Vg63A57rHxrV0y1/n0KMEMLcyupXkZX8Y3HSU8MD0e/JtvxM938OZoAyBFOBWbuDhCKUaYvYWI+yLkkXbRz6NPEGkk9nUpqp/MIMahcZI0fz08UIQifsQ051wEM4kVufGljRXkXCf9TVkRytErf+HqDJUDOiB7LQ=

  file_glob: true
  file: $CRATE_NAME-$TRAVIS_TAG-$TARGET.*
  on:
    condition: $TRAVIS_RUST_VERSION = stable
    tags: true
  provider: releases
  skip_cleanup: true

cache: cargo
before_cache:
  - chmod -R a+r $HOME/.cargo

branches:
  only:
    - master

notifications:
  email:
    on_success: never
